# Generated by Django 4.2.dev20221028064633 on 2023-03-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dosage_instructions',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity',
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='dosage_instructions',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
