# Generated by Django 4.2.dev20221028064633 on 2023-03-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_prescription_dosage_instructions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name']},
        ),
    ]
