# Generated by Django 4.2.dev20221028064633 on 2023-03-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_medicine_description_medicine_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('total_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ATMMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_level', models.IntegerField(default=0)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.atm')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='atm',
            name='medicines',
            field=models.ManyToManyField(through='pharmacy.ATMMedicine', to='pharmacy.medicine'),
        ),
    ]
