# Generated by Django 4.2.dev20221028064633 on 2023-03-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
